### ISSUE TITLE
Swap Error

### ISSUE THREAD

**Issue by sowell-owen** [symbiosis-finance/js-sdk#61]
Hello, I'm trying to swap ETH on USDC on ZkSync Era mainnet using symbiosis js sdk.

Here's the source code: https://gist.github.com/sowell-owen/63990c376c256231bef580356c1f5249
Here's the error: https://gist.github.com/sowell-owen/3fa56b0c86d563cae14afad2de091ec4

What's wrong? Thanks in advance!

**Comment by sowell-owen** [comment]
> Hello! It appears that you are attempting to swap assets within the same network. Currently, our SDK only supports crosschain swaps.

Hello, thanks for the reply. How can I swap assets within the same network through Symbiosis then? Any solution to that?

**Comment by mxck** [comment]
There is no such feature for now, but we would like to add this feature in the near future.
Historically our SDK has been only used for crosschain swaps.

**Comment by sowell-owen** [comment]
> There is no such feature for now, but we would like to add this feature in the near future. Historically our SDK has been only used for crosschain swaps.

I got it, how can I do this without SDK?

**Comment by mxck** [comment]
You can use one of our aggregators partners directly: [1inch](https://1inch.io/api/), [OpenOcean](https://openocean.finance/api/api-sdk/) or [OKX](https://www.okx.com/web3/build/docs/dex/dex_api)
